# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
destination: build

title: Cirkut Media
email: josh@cirkut.net
description: Cirkut Media is a marketing and media agency that helps connect the dots between you and your customers.
baseurl: "https://cirkut.io"
url: "https://cirkut.io"
timezone: America/Detroit

twitter_username: cirkutmedia
github_username:  cirkut

# Build settings
markdown: kramdown

defaults:
  -
    values:
      author: Josh Allen
      layout: blog
